/* FractureBridge — demonstration dataset and workflow constants.
 * All patients are fictional. No real or deidentified clinical data is used.
 */

export const cx = (...a) => a.filter(Boolean).join(" ");

/* ---------------------------- care team ---------------------------- */

export const TEAM = [
  "A. Ruiz, RN — Fracture Liaison",
  "M. Okafor, NP — Bone Health Clinic",
  "Dr. L. Hahn — Primary Care",
];

/* ------------------------- the seven stages ------------------------ */
/* These are the piers of the bridge. Each one has a named owner.      */

export const STAGES = [
  { key: "reported", label: "Fracture reported", by: "Radiology" },
  { key: "flagged", label: "Gap identified", by: "FractureBridge" },
  { key: "review", label: "Human review", by: "Fracture liaison" },
  { key: "owned", label: "Owner assigned", by: "Named person" },
  { key: "contacted", label: "Patient contacted", by: "Care team" },
  { key: "arranged", label: "Evaluation arranged", by: "Ordering clinician" },
  { key: "closed", label: "Plan documented", by: "Clinician of record" },
];

export const STAGE_INDEX = {
  review: 2,
  owned: 3,
  contacted: 4,
  arranged: 5,
  documented: 6,
  closed: 7,
};

export const LANES = [
  { key: "review", label: "Needs review" },
  { key: "owned", label: "Owned" },
  { key: "contacted", label: "Patient contacted" },
  { key: "arranged", label: "Evaluation arranged" },
  { key: "documented", label: "Plan documented" },
  { key: "closed", label: "Closed" },
];

export const EXCLUSION_REASONS = [
  "High-energy trauma — not eligible for this pathway",
  "Pathologic fracture — known malignancy",
  "Degenerative change / Schmorl node — not a fracture",
  "Duplicate of an existing case",
  "Report extraction error",
];

/* --------------------------- demo dataset -------------------------- */

const fu = (label, status, source, lookback, note) => ({
  label,
  status,
  source,
  lookback,
  note,
});

export const MARGARET_REPORT = [
  { t: "EXAM: CT abdomen and pelvis with IV contrast.", head: true },
  {
    t: "INDICATION: 74-year-old woman with three days of right lower quadrant pain and low-grade fever.",
  },
  { t: "FINDINGS", head: true },
  {
    t: "Bowel: Wall thickening of the terminal ileum with adjacent fat stranding, consistent with ileitis. No free air. No abscess.",
  },
  {
    t: "Solid organs: Liver, spleen, pancreas, adrenals and kidneys unremarkable. No hydronephrosis.",
  },
  {
    t: "Vascular: Aortic atherosclerotic calcification without aneurysm.",
  },
  {
    t: "Osseous structures: Chronic-appearing compression deformity of the L1 vertebral body with approximately 30% anterior height loss and no retropulsion. Degenerative changes of the lower lumbar spine.",
    hl: true,
  },
  { t: "IMPRESSION", head: true },
  { t: "1. Terminal ileitis. Correlate clinically." },
  { t: "2. No abscess or perforation." },
  {
    t: "3. Chronic-appearing L1 vertebral compression deformity. Correlate with clinical and bone-health history.",
    hl: true,
  },
];

export const CASES = [
  {
    id: "FB-04417",
    name: "Margaret Ellison",
    age: 74,
    sex: "F",
    mrn: "DEMO-88214",
    exam: "CT abdomen/pelvis with contrast",
    indication: "Right lower quadrant pain",
    reportDate: "May 2, 2026",
    days: 102,
    finding: "Chronic L1 vertebral compression deformity",
    level: "L1",
    chronicity: "Chronic-appearing",
    confidence: "Explicit report language",
    priority: "High",
    priorityFactors: [
      "Age 74",
      "Prior low-trauma fracture documented (distal radius, 2024)",
      "No relevant bone-health follow-up evidence found in the connected demonstration record",
      "Report language explicit, not equivocal",
    ],
    report: MARGARET_REPORT,
    verify: [
      "Confirm whether the L1 deformity is consistent with a fragility-fracture context and not traumatic or pathologic",
      "Confirm the 2024 wrist fracture was low-energy",
      "Confirm no bone-health care is being delivered outside this health system",
    ],
    followUp: [
      fu("DXA / BMD result", "none", "Imaging results feed", "24 months", "No study on file"),
      fu("DXA order", "none", "Orders", "24 months", "No order placed"),
      fu("Osteoporosis pharmacotherapy", "none", "Medication list", "12 months", "No bisphosphonate, denosumab, or anabolic agent"),
      fu("Calcium / vitamin D", "partial", "Medication list", "12 months", "Vitamin D 1000 IU on the home list — supplementation alone is not an osteoporosis evaluation"),
      fu("Bone-health or FLS referral", "none", "Referrals", "24 months", "No referral found"),
      fu("Endocrinology referral", "none", "Referrals", "24 months", "No referral found"),
      fu("Osteoporosis assessment in notes", "none", "Note text", "24 months", "No documented assessment or discussion"),
      fu("Prior fracture history", "found", "Problem list / imaging", "5 years", "Distal radius fracture, March 2024 — raises priority, does not close the gap"),
      fu("Documented clinical review of this finding", "none", "Note text", "Since report date", "No note references the L1 finding"),
    ],
    stage: "review",
    owner: null,
    letterApproved: false,
    letter:
      "Dear Ms. Ellison,\n\nWhen you had your CT scan on May 2, the radiology report noted a compression deformity in one of the bones of your spine (the L1 vertebra). This finding was not the reason for your scan.\n\nIn some adults, this type of finding may be associated with weakened bone and may warrant additional bone-health review.\n\nYour care team would like to review whether additional bone-health evaluation may be appropriate for you. Someone from our office will contact you to discuss the next step.\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "May 2, 2026 · 4:12p", actor: "Radiology", text: "Report finalized by radiologist." },
      {
        ts: "May 3, 2026 · 2:05a",
        actor: "FractureBridge",
        ai: true,
        text: "Report screened. Vertebral compression-fracture language identified in Findings and Impression; human review required.",
      },
      {
        ts: "May 3, 2026 · 2:05a",
        actor: "FractureBridge",
        ai: true,
        text: "Follow-up check run across 9 sources. No relevant bone-health follow-up evidence found in the connected demonstration record.",
      },
      {
        ts: "May 3, 2026 · 2:06a",
        actor: "FractureBridge",
        ai: true,
        text: "Case placed on the review worklist. Priority: High. No clinical action taken.",
      },
    ],
  },
  {
    id: "FB-04392",
    name: "Doris Whitfield",
    age: 81,
    sex: "F",
    mrn: "DEMO-88103",
    exam: "Lumbar spine radiograph, 2 views",
    indication: "Chronic low back pain",
    reportDate: "Jun 14, 2026",
    days: 59,
    finding: "T12 wedge deformity, age indeterminate",
    level: "T12",
    chronicity: "Age indeterminate",
    confidence: "Equivocal report language",
    priority: "High",
    priorityFactors: ["Age 81", "No follow-up evidence found in the demonstration record"],
    report: [
      { t: "EXAM: Lumbar spine, AP and lateral.", head: true },
      { t: "INDICATION: 81-year-old woman with chronic low back pain." },
      { t: "FINDINGS", head: true },
      {
        t: "Mild wedge deformity of the T12 vertebral body, approximately 20% anterior height loss, age indeterminate. Multilevel disc space narrowing.",
        hl: true,
      },
      { t: "IMPRESSION", head: true },
      { t: "1. T12 wedge deformity, age indeterminate. 2. Lumbar spondylosis.", hl: true },
    ],
    verify: [
      "Report language is equivocal — confirm this represents a fracture rather than a developmental or degenerative deformity",
      "Confirm no bone-health care outside this health system",
    ],
    followUp: [
      fu("DXA / BMD result", "none", "Imaging results feed", "24 months", "No study on file"),
      fu("DXA order", "none", "Orders", "24 months", "No order placed"),
      fu("Osteoporosis pharmacotherapy", "none", "Medication list", "12 months", "None found"),
      fu("Bone-health or FLS referral", "none", "Referrals", "24 months", "No referral found"),
      fu("Osteoporosis assessment in notes", "none", "Note text", "24 months", "No documented assessment"),
      fu("Prior fracture history", "none", "Problem list / imaging", "5 years", "None found"),
    ],
    stage: "review",
    owner: null,
    letterApproved: false,
    letter:
      "Dear Ms. Whitfield,\n\nYour recent spine X-ray showed a change in the shape of one of your vertebrae that can sometimes be caused by weakened bone. Your care team would like to review whether a bone-health check would be helpful.\n\nSomeone from our office will call you.\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "Jun 14, 2026 · 11:20a", actor: "Radiology", text: "Report finalized by radiologist." },
      {
        ts: "Jun 15, 2026 · 2:03a",
        actor: "FractureBridge",
        ai: true,
        text: "Flagged for review. Report language equivocal — human verification required before any action.",
      },
    ],
  },
  {
    id: "FB-04408",
    name: "Ronald Vasquez",
    age: 69,
    sex: "M",
    mrn: "DEMO-88450",
    exam: "Low-dose CT chest (lung cancer screening)",
    indication: "Screening, former smoker",
    reportDate: "Jul 1, 2026",
    days: 42,
    finding: "Mild T8 compression deformity",
    level: "T8",
    chronicity: "Chronic-appearing",
    confidence: "Explicit report language",
    priority: "Medium",
    priorityFactors: ["Age 69", "Long-term inhaled and oral steroid use on medication list", "No follow-up evidence found"],
    report: [
      { t: "EXAM: Low-dose CT chest without contrast.", head: true },
      { t: "INDICATION: Lung cancer screening, 69-year-old former smoker." },
      { t: "FINDINGS", head: true },
      { t: "Lungs: 4 mm right upper lobe nodule, Lung-RADS 2. No consolidation." },
      {
        t: "Osseous: Mild chronic compression deformity of T8 with approximately 20% height loss.",
        hl: true,
      },
      { t: "IMPRESSION", head: true },
      { t: "1. Lung-RADS 2. Continue annual screening. 2. Chronic T8 compression deformity.", hl: true },
    ],
    verify: [
      "Confirm glucocorticoid exposure and duration with the prescribing clinician",
      "Confirm the deformity is not post-traumatic",
    ],
    followUp: [
      fu("DXA / BMD result", "none", "Imaging results feed", "24 months", "No study on file"),
      fu("Osteoporosis pharmacotherapy", "none", "Medication list", "12 months", "None found"),
      fu("Bone-health or FLS referral", "none", "Referrals", "24 months", "None found"),
      fu("Osteoporosis assessment in notes", "none", "Note text", "24 months", "None found"),
      fu("Glucocorticoid exposure", "found", "Medication list", "24 months", "Prednisone courses x3 and chronic inhaled steroid — raises priority"),
    ],
    stage: "review",
    owner: null,
    letterApproved: false,
    letter:
      "Dear Mr. Vasquez,\n\nYour recent CT scan noted a compression deformity in one of the bones of your mid-back. In some adults, this type of finding may be associated with weakened bone. Your care team would like to review whether additional bone-health evaluation may be appropriate.\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "Jul 1, 2026 · 9:02a", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Jul 2, 2026 · 2:04a", actor: "FractureBridge", ai: true, text: "Flagged for review. Priority: Medium." },
    ],
  },
  {
    id: "FB-04371",
    name: "Patricia Nam",
    age: 77,
    sex: "F",
    mrn: "DEMO-87990",
    exam: "CT abdomen/pelvis",
    indication: "Diverticulitis follow-up",
    reportDate: "Apr 18, 2026",
    days: 116,
    finding: "L2 compression deformity",
    level: "L2",
    chronicity: "Chronic-appearing",
    confidence: "Explicit report language",
    priority: "High",
    priorityFactors: ["Age 77", "No follow-up evidence found in the demonstration record"],
    report: [
      { t: "EXAM: CT abdomen and pelvis.", head: true },
      { t: "FINDINGS", head: true },
      { t: "Resolved sigmoid diverticulitis. No abscess." },
      { t: "Osseous: Chronic L2 compression deformity with 25% height loss.", hl: true },
    ],
    verify: ["Confirm low-energy mechanism", "Confirm no outside bone-health care"],
    followUp: [
      fu("DXA / BMD result", "none", "Imaging results feed", "24 months", "No study on file"),
      fu("Osteoporosis pharmacotherapy", "none", "Medication list", "12 months", "None found"),
      fu("Bone-health or FLS referral", "none", "Referrals", "24 months", "None found"),
      fu("Osteoporosis assessment in notes", "none", "Note text", "24 months", "None found"),
    ],
    stage: "owned",
    owner: TEAM[0],
    letterApproved: false,
    letter:
      "Dear Ms. Nam,\n\nYour recent CT scan noted a compression fracture in your spine. Your care team would like to review whether a bone-health evaluation would be helpful.\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "Apr 18, 2026 · 3:40p", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Apr 19, 2026 · 2:02a", actor: "FractureBridge", ai: true, text: "Flagged for review. No follow-up evidence found in the connected demonstration record." },
      { ts: "Apr 21, 2026 · 10:15a", actor: TEAM[0], text: "Care gap confirmed after chart review. Case assigned." },
    ],
  },
  {
    id: "FB-04350",
    name: "Gloria Adeyemi",
    age: 72,
    sex: "F",
    mrn: "DEMO-87741",
    exam: "MRI lumbar spine",
    indication: "New back pain",
    reportDate: "Mar 30, 2026",
    days: 135,
    finding: "T11 compression fracture with marrow edema",
    level: "T11",
    chronicity: "Acute or subacute",
    confidence: "Explicit report language",
    priority: "High",
    priorityFactors: ["Age 72", "Acute fracture with edema", "No follow-up evidence found"],
    report: [
      { t: "EXAM: MRI lumbar spine without contrast.", head: true },
      { t: "FINDINGS", head: true },
      { t: "T11 compression fracture with marrow edema, suggesting acute or subacute injury. No retropulsion or cord compression.", hl: true },
    ],
    verify: ["Confirm low-energy mechanism", "Confirm pain management plan is in place"],
    followUp: [
      fu("DXA / BMD result", "none", "Imaging results feed", "24 months", "No study on file"),
      fu("Osteoporosis pharmacotherapy", "none", "Medication list", "12 months", "None found"),
      fu("Bone-health or FLS referral", "none", "Referrals", "24 months", "None found"),
    ],
    stage: "contacted",
    owner: TEAM[1],
    letterApproved: true,
    letter:
      "Dear Ms. Adeyemi,\n\nYour recent MRI showed a compression fracture in your spine. Your care team would like to check whether a bone-health evaluation would help lower the chance of another fracture.\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "Mar 30, 2026 · 1:10p", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Mar 31, 2026 · 2:01a", actor: "FractureBridge", ai: true, text: "Flagged for review." },
      { ts: "Apr 2, 2026 · 9:30a", actor: TEAM[1], text: "Care gap confirmed. Case assigned." },
      { ts: "Apr 4, 2026 · 11:00a", actor: TEAM[1], text: "Patient letter approved and sent. Phone outreach completed — patient agreeable to evaluation." },
    ],
  },
  {
    id: "FB-04333",
    name: "Frances Boyle",
    age: 84,
    sex: "F",
    mrn: "DEMO-87502",
    exam: "CT chest without contrast",
    indication: "Chronic cough",
    reportDate: "Mar 9, 2026",
    days: 156,
    finding: "T12 compression deformity noted incidentally",
    level: "T12",
    chronicity: "Chronic-appearing",
    confidence: "Probable report language",
    priority: "High",
    priorityFactors: ["Age 84", "Fall history", "No follow-up evidence found"],
    report: [
      { t: "EXAM: CT chest without contrast.", head: true },
      { t: "INDICATION: Chronic cough.", head: false },
      { t: "FINDINGS", head: true },
      { t: "Osseous structures: Chronic-appearing T12 vertebral compression deformity with mild anterior height loss. No acute osseous abnormality identified.", hl: true },
    ],
    verify: ["Confirm fracture context and whether bone-health follow-up is already occurring outside the connected record"],
    followUp: [
      fu("DXA / BMD result", "none", "Imaging results feed", "24 months", "No study on file"),
      fu("Bone-health or FLS referral", "none", "Referrals", "24 months", "None found"),
      fu("Falls assessment", "found", "Note text", "12 months", "Falls screening documented — relevant but not a bone-health evaluation"),
    ],
    stage: "arranged",
    owner: TEAM[2],
    letterApproved: true,
    letter: "Dear Ms. Boyle,\n\nYour recent CT report noted a compression deformity in your spine...\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "Mar 9, 2026 · 8:45a", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Mar 10, 2026 · 2:02a", actor: "FractureBridge", ai: true, text: "Flagged for review." },
      { ts: "Mar 12, 2026 · 1:20p", actor: TEAM[0], text: "Care gap confirmed. Assigned to primary care." },
      { ts: "Mar 18, 2026 · 4:05p", actor: TEAM[2], text: "Patient contacted. DXA ordered." },
      { ts: "Mar 26, 2026 · 9:00a", actor: TEAM[2], text: "DXA scheduled for Apr 9." },
    ],
  },
  {
    id: "FB-04321",
    name: "Nancy Oyelaran",
    age: 73,
    sex: "F",
    mrn: "DEMO-87388",
    exam: "CT abdomen/pelvis",
    indication: "Abdominal pain",
    reportDate: "Feb 24, 2026",
    days: 169,
    finding: "L3 compression deformity",
    level: "L3",
    chronicity: "Chronic-appearing",
    confidence: "Explicit report language",
    priority: "Medium",
    priorityFactors: ["Age 73", "No follow-up evidence found at time of flag"],
    report: [
      { t: "EXAM: CT abdomen and pelvis.", head: true },
      { t: "FINDINGS", head: true },
      { t: "Chronic L3 compression deformity with 20% height loss.", hl: true },
    ],
    verify: ["Confirm treatment plan documented by treating clinician"],
    followUp: [
      fu("DXA / BMD result", "found", "Imaging results feed", "24 months", "DXA completed Apr 14, 2026 — T-score -2.8 (after FractureBridge outreach)"),
      fu("Osteoporosis pharmacotherapy", "found", "Medication list", "12 months", "Alendronate started Apr 22, 2026"),
      fu("Bone-health or FLS referral", "found", "Referrals", "24 months", "Bone Health Clinic, Apr 2026"),
    ],
    stage: "documented",
    owner: TEAM[1],
    letterApproved: true,
    letter: "Dear Ms. Oyelaran,\n\nYour recent CT scan noted a compression fracture...\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "Feb 24, 2026 · 2:30p", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Feb 25, 2026 · 2:03a", actor: "FractureBridge", ai: true, text: "Flagged for review. No follow-up evidence found in the connected demonstration record." },
      { ts: "Feb 27, 2026 · 10:00a", actor: TEAM[0], text: "Care gap confirmed. Assigned to Bone Health Clinic." },
      { ts: "Mar 4, 2026 · 3:15p", actor: TEAM[1], text: "Patient letter approved and sent. Outreach call completed." },
      { ts: "Apr 14, 2026 · 11:00a", actor: TEAM[1], text: "DXA completed. T-score -2.8." },
      { ts: "Apr 22, 2026 · 9:40a", actor: TEAM[1], text: "Treatment plan documented: alendronate, vitamin D, follow-up in 12 months." },
    ],
  },
  {
    id: "FB-04298",
    name: "Helen Marchetti",
    age: 79,
    sex: "F",
    mrn: "DEMO-87145",
    exam: "CT abdomen/pelvis",
    indication: "Hematuria",
    reportDate: "Jan 12, 2026",
    days: 212,
    finding: "L1 compression deformity",
    level: "L1",
    chronicity: "Chronic-appearing",
    confidence: "Explicit report language",
    priority: "Medium",
    priorityFactors: ["Age 79", "No follow-up evidence found at time of flag"],
    report: [
      { t: "EXAM: CT abdomen and pelvis.", head: true },
      { t: "FINDINGS", head: true },
      { t: "Chronic L1 compression deformity. No acute osseous abnormality.", hl: true },
    ],
    verify: [],
    followUp: [
      fu("DXA / BMD result", "found", "Imaging results feed", "24 months", "DXA completed Feb 20, 2026 — T-score -2.5"),
      fu("Osteoporosis pharmacotherapy", "found", "Medication list", "12 months", "Denosumab started Mar 2026"),
      fu("Osteoporosis assessment in notes", "found", "Note text", "24 months", "Bone Health Clinic note, Mar 3, 2026"),
    ],
    stage: "closed",
    owner: TEAM[1],
    letterApproved: true,
    letter: "Dear Ms. Marchetti,\n\nYour recent CT scan noted a compression fracture...\n\n— Bone Health Program, Austin market",
    audit: [
      { ts: "Jan 12, 2026 · 4:00p", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Jan 13, 2026 · 2:01a", actor: "FractureBridge", ai: true, text: "Flagged for review. No follow-up evidence found in the connected demonstration record." },
      { ts: "Jan 15, 2026 · 9:20a", actor: TEAM[0], text: "Care gap confirmed. Assigned." },
      { ts: "Jan 20, 2026 · 2:00p", actor: TEAM[1], text: "Patient letter approved and sent. Outreach completed." },
      { ts: "Feb 20, 2026 · 10:30a", actor: TEAM[1], text: "DXA completed. T-score -2.5." },
      { ts: "Mar 3, 2026 · 11:15a", actor: TEAM[1], text: "Treatment plan documented. Denosumab started." },
      { ts: "Mar 3, 2026 · 11:18a", actor: TEAM[1], text: "Loop closed: evaluation completed and plan documented." },
    ],
  },
  {
    id: "FB-04361",
    name: "Wanda Pryce",
    age: 76,
    sex: "F",
    mrn: "DEMO-87866",
    exam: "CT abdomen/pelvis",
    indication: "Abdominal pain",
    reportDate: "Apr 8, 2026",
    days: 126,
    finding: "T7 compression deformity",
    level: "T7",
    chronicity: "Chronic-appearing",
    confidence: "Explicit report language",
    priority: "—",
    priorityFactors: [],
    report: [
      { t: "EXAM: CT abdomen and pelvis.", head: true },
      { t: "FINDINGS", head: true },
      { t: "Chronic T7 compression deformity, stable compared with prior study.", hl: true },
    ],
    verify: [],
    followUp: [
      fu("DXA / BMD result", "found", "Imaging results feed", "24 months", "DXA completed Aug 2025 — T-score -2.6"),
      fu("Osteoporosis pharmacotherapy", "found", "Medication list", "12 months", "Alendronate 70 mg weekly, active"),
      fu("Osteoporosis assessment in notes", "found", "Note text", "24 months", "Endocrinology note, Sep 2025"),
    ],
    stage: "verified",
    owner: null,
    letterApproved: false,
    letter: "",
    audit: [
      { ts: "Apr 8, 2026 · 5:12p", actor: "Radiology", text: "Report finalized by radiologist." },
      {
        ts: "Apr 9, 2026 · 2:02a",
        actor: "FractureBridge",
        ai: true,
        text: "Fracture language identified. Follow-up check found active osteoporosis treatment and a DXA within 24 months. No worklist entry created. Logged for audit only.",
      },
    ],
  },
  {
    id: "FB-04344",
    name: "Edward Kalinowski",
    age: 71,
    sex: "M",
    mrn: "DEMO-87610",
    exam: "CT thoracic spine",
    indication: "Motor vehicle collision",
    reportDate: "Mar 20, 2026",
    days: 145,
    finding: "T12 burst fracture",
    level: "T12",
    chronicity: "Acute",
    confidence: "Explicit report language",
    priority: "—",
    priorityFactors: [],
    report: [
      { t: "EXAM: CT thoracic spine.", head: true },
      { t: "INDICATION: Restrained driver, high-speed motor vehicle collision." },
      { t: "FINDINGS", head: true },
      { t: "Acute T12 burst fracture with 40% height loss and mild retropulsion.", hl: true },
    ],
    verify: [],
    followUp: [
      fu("DXA / BMD result", "none", "Imaging results feed", "24 months", "No study on file"),
      fu("Spine surgery involvement", "found", "Referrals", "12 months", "Admitted, managed by spine service"),
    ],
    stage: "excluded",
    excludeReason: "High-energy trauma — not eligible for this bone-health pathway",
    owner: TEAM[0],
    letterApproved: false,
    letter: "",
    audit: [
      { ts: "Mar 20, 2026 · 7:40p", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Mar 21, 2026 · 2:01a", actor: "FractureBridge", ai: true, text: "Flagged for review — mechanism not determinable from report text alone." },
      { ts: "Mar 21, 2026 · 8:30a", actor: TEAM[0], text: "Excluded after review: high-energy trauma. Reason recorded for false-positive analysis." },
    ],
  },
  {
    id: "FB-04310",
    name: "Yolanda Rios",
    age: 68,
    sex: "F",
    mrn: "DEMO-87299",
    exam: "CT chest/abdomen/pelvis",
    indication: "Restaging, breast carcinoma",
    reportDate: "Feb 5, 2026",
    days: 188,
    finding: "L3 pathologic compression fracture",
    level: "L3",
    chronicity: "Acute",
    confidence: "Explicit report language",
    priority: "—",
    priorityFactors: [],
    report: [
      { t: "EXAM: CT chest, abdomen and pelvis.", head: true },
      { t: "FINDINGS", head: true },
      { t: "New L3 compression fracture through a lytic lesion, consistent with pathologic fracture in the setting of known metastatic disease.", hl: true },
    ],
    verify: [],
    followUp: [
      fu("Oncology involvement", "found", "Referrals", "12 months", "Active oncology care, radiation oncology consulted"),
    ],
    stage: "excluded",
    excludeReason: "Pathologic fracture — known malignancy",
    owner: TEAM[0],
    letterApproved: false,
    letter: "",
    audit: [
      { ts: "Feb 5, 2026 · 3:22p", actor: "Radiology", text: "Report finalized by radiologist." },
      { ts: "Feb 6, 2026 · 2:03a", actor: "FractureBridge", ai: true, text: "Flagged for review — malignancy context present in report." },
      { ts: "Feb 6, 2026 · 9:10a", actor: TEAM[0], text: "Excluded after review: pathologic fracture, managed by oncology." },
    ],
  },
];

/* ---------------------- visual language ---------------------------- *
 * One colour per workflow stage, used identically on the bridge, the
 * board, the queue dots and the charts. Colour carries state, never
 * decoration.
 * ------------------------------------------------------------------ */

export const STAGE_STYLE = {
  review: {
    name: "Needs review",
    dot: "bg-amber-500",
    soft: "bg-amber-50",
    text: "text-amber-800",
    ring: "border-amber-200",
    bar: "bg-amber-500",
    hex: "#f59e0b",
  },
  owned: {
    name: "Owned",
    dot: "bg-sky-500",
    soft: "bg-sky-50",
    text: "text-sky-800",
    ring: "border-sky-200",
    bar: "bg-sky-500",
    hex: "#0ea5e9",
  },
  contacted: {
    name: "Patient contacted",
    dot: "bg-indigo-500",
    soft: "bg-indigo-50",
    text: "text-indigo-800",
    ring: "border-indigo-200",
    bar: "bg-indigo-500",
    hex: "#6366f1",
  },
  arranged: {
    name: "Evaluation arranged",
    dot: "bg-teal-500",
    soft: "bg-teal-50",
    text: "text-teal-800",
    ring: "border-teal-200",
    bar: "bg-teal-500",
    hex: "#14b8a6",
  },
  documented: {
    name: "Plan documented",
    dot: "bg-emerald-500",
    soft: "bg-emerald-50",
    text: "text-emerald-800",
    ring: "border-emerald-200",
    bar: "bg-emerald-500",
    hex: "#10b981",
  },
  closed: {
    name: "Closed",
    dot: "bg-slate-400",
    soft: "bg-slate-100",
    text: "text-slate-600",
    ring: "border-slate-200",
    bar: "bg-slate-400",
    hex: "#94a3b8",
  },
  verified: {
    name: "Follow-up verified",
    dot: "bg-slate-300",
    soft: "bg-slate-50",
    text: "text-slate-500",
    ring: "border-slate-200",
    bar: "bg-slate-300",
    hex: "#cbd5e1",
  },
  excluded: {
    name: "Excluded",
    dot: "bg-slate-300",
    soft: "bg-slate-50",
    text: "text-slate-500",
    ring: "border-slate-200",
    bar: "bg-slate-300",
    hex: "#cbd5e1",
  },
};

export const AI_HEX = "#7c3aed";
export const HUMAN_HEX = "#0f766e";

/* ------------------------- pilot instrumentation ------------------- */
/* Simulated figures for the demonstration. Replace with real pilot     */
/* extracts before any of this is shown as evidence.                    */

export const SCREEN_FUNNEL = [
  { step: "Reports screened", n: 12480, hex: "#cbd5e1" },
  { step: "Fracture language", n: 412, hex: "#a5b4fc" },
  { step: "Unique patients", n: 268, hex: "#6366f1" },
  { step: "Care gaps routed", n: 97, hex: "#f59e0b" },
];

export const EXCLUSION_DATA = [
  { reason: "High-energy trauma", n: 5 },
  { reason: "Pathologic fracture", n: 3 },
  { reason: "Care outside system", n: 3 },
  { reason: "Degenerative change", n: 2 },
];

export const WEEKLY = [
  { w: "W1", found: 5, closed: 0 },
  { w: "W3", found: 4, closed: 1 },
  { w: "W5", found: 6, closed: 2 },
  { w: "W7", found: 3, closed: 3 },
  { w: "W9", found: 5, closed: 4 },
  { w: "W11", found: 4, closed: 3 },
  { w: "W13", found: 4, closed: 5 },
  { w: "W15", found: 3, closed: 4 },
  { w: "W17", found: 5, closed: 5 },
  { w: "W19", found: 4, closed: 6 },
  { w: "W21", found: 3, closed: 5 },
  { w: "W23", found: 4, closed: 6 },
  { w: "W25", found: 3, closed: 5 },
];

export const CASCADE = [
  { step: "Care gaps confirmed", n: 84, hex: "#f59e0b" },
  { step: "Patient outreach completed", n: 71, hex: "#0ea5e9" },
  { step: "Bone-health evaluation completed", n: 44, hex: "#6366f1" },
  { step: "DXA completed", n: 38, hex: "#14b8a6" },
  { step: "Therapy started", n: 21, hex: "#10b981" },
];

export const BASELINE = [
  { period: "12 months before", pct: 19 },
  { period: "Pilot period", pct: 52 },
];
